Data Context- 
The dataset contains transactions made by credit cards in September 2013 by European cardholders.
This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-sensitive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise. 

In [1]:
#importing Required Libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from imblearn.over_sampling import SMOTE

from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,classification_report

In [41]:
#Loading Files
df = pd.read_csv(r"C:\Users\ramni\Downloads\archive(8)\creditcard.csv")
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [4]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

Checking any null values

In [5]:
df.isnull().sum().sum()

0

Checking Duplicates

In [6]:
df.duplicated().sum()

1081

In [7]:
(df.duplicated().sum()/df.shape[0])*100

0.379555277784605

Deleting Duplicates

In [42]:
df = df.drop_duplicates()
df.shape

(283726, 31)

Cheking Correletion

In [9]:
plt.figure(figsize = (20,10))
sns.heatmap(df.corr(),cmap = 'PuBuGn')

<Axes: >

In [10]:
correlation_matrix = df.corr()
np.fill_diagonal(correlation_matrix.values, np.nan)
max_corr_value = correlation_matrix.abs().max().max()
max_corr_vars = correlation_matrix.stack().abs().idxmax()
print(f"Maximum absolute correlation: {max_corr_value:.2f} between variables: {max_corr_vars}")


Maximum absolute correlation: 0.53 between variables: ('V2', 'Amount')


The maximum corelation is .53(in absolute terms) between variables

In [11]:
df["Class"].value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [12]:
plt.figure(figsize = (10,5))
plt.title('Pie chart for Class')
plt.pie(df['Class'].value_counts(),labels = df['Class'].unique(),autopct = "%1.1f%%");

As we can Seen the data is highly imbalanced 99.8% is 0(No fradulent transaction) only .2% is fradulent one

In [13]:
df.groupby("Class")[["Amount","Time"]].mean()


Amount          Time
Class                          
0       88.413575  94835.058093
1      123.871860  80450.513742

In [14]:
df.groupby("Class")[["Amount","Time"]].median()

Amount     Time
Class                 
0       22.00  84711.0
1        9.82  73408.0

From the above data we see that Amount is relatively small or very high for fraud 

Standardizing the values of Amount and Time so that it can be feed into the model 

In [16]:

scaler = StandardScaler() 
df.loc[:, "Amount"] = scaler.fit_transform(df[['Amount']])

# Scale the 'Time' column
df.loc[:, 'Time'] = scaler.fit_transform(df[['Time']])

In [17]:
df

Time         V1         V2        V3        V4        V5  \
0      -1.996823  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1      -1.996823   1.191857   0.266151  0.166480  0.448154  0.060018   
2      -1.996802  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3      -1.996802  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4      -1.996781  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  1.642235 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  1.642257  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  1.642278   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  1.642278  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  1.642362  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28    Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  0.244200   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724 -0.342584   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  1.158900   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  0.139886   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153 -0.073813   
...          ...       ...       ...       ...       ...       ...       ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731 -0.350252   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527 -0.254325   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561 -0.082239   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533 -0.313391   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  0.513290   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[283726 rows x 31 columns]

In [18]:
X = df.drop(columns = 'Class')
y = df['Class']

In [19]:
X.shape

(283726, 30)

In [20]:
y.shape

(283726,)

Creating Balanced dataset by oversampling (since by undersampling we might lose valuable information

In [21]:
smote = SMOTE(random_state = 42)
X_resampled,y_resampled = smote.fit_resample(X,y)

In [22]:
y_resampled.value_counts()

Class
0    283253
1    283253
Name: count, dtype: int64

For the classification problem at hand, we will evaluate three models: Logistic Regression, Random Forest, and Decision Tree. After implementing these models and analyzing their performance metrics, we will select the most suitable model for our final choice.

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,train_size=.8,random_state=42)

Modeling using LogisticRegression

In [25]:
log_regg = LogisticRegression()
log_regg.fit(X_train,y_train)
test_pred = log_regg.predict(X_test)
test_pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [26]:
accuracy_score(y_test,test_pred)

0.9452613369578649

In [27]:
confusion_matrix(y_test,test_pred)

array([[54996,  1467],
       [ 4735, 52104]], dtype=int64)

In [28]:
f1_score(y_test,test_pred)

0.9438275518521873

In [29]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.95     56463
           1       0.97      0.92      0.94     56839

    accuracy                           0.95    113302
   macro avg       0.95      0.95      0.95    113302
weighted avg       0.95      0.95      0.95    113302



Modeling using RandomForest

In [31]:
rand_ = RandomForestClassifier()
rand_.fit(X_train,y_train) 
test_pred = rand_.predict(X_test)
test_pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [32]:
accuracy_score(y_test,test_pred)

0.9999029143351397

In [33]:
confusion_matrix(y_test,test_pred)

array([[56452,    11],
       [    0, 56839]], dtype=int64)

In [34]:
f1_score(y_test,test_pred)

0.9999032448170008

In [35]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56463
           1       1.00      1.00      1.00     56839

    accuracy                           1.00    113302
   macro avg       1.00      1.00      1.00    113302
weighted avg       1.00      1.00      1.00    113302



Modeling using Decision Tree

In [37]:
Desc_Tree = tree.DecisionTreeClassifier()
Desc_Tree.fit(X_train,y_train)
test_pred = Desc_Tree.predict(X_test)
test_pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [38]:
accuracy_score(y_test,test_pred)

0.9982877619106458

In [39]:
confusion_matrix(y_test,test_pred)

array([[56314,   149],
       [   45, 56794]], dtype=int64)

In [40]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56463
           1       1.00      1.00      1.00     56839

    accuracy                           1.00    113302
   macro avg       1.00      1.00      1.00    113302
weighted avg       1.00      1.00      1.00    113302



The Random Forest model has demonstrated superior performance across all metrics, achieving the highest accuracy and F1 score. Additionally, upon examining the confusion matrix, we observe that only 11 instances were misclassified. Therefore, it can be concluded that Random Forest is theoretically the best model for this task.
